### ISSUE TITLE
Apple domain changes

### ISSUE THREAD

**Issue by cyanzhong** [axelburks/JSBox#1]
Apple changed `itunes.apple.com` to `apps.apple.com` for some scenarios, which means we need to change regex pattern to something like `(itunes|apps)`. Note that, lookup API isn't affected.

I'm going to fix my implementation here: https://github.com/cyanzhong/xTeko/tree/master/extension-scripts/itunes-search

Since you made some great changes in your fork, I think you can handle it.

**Comment by axelburks** [comment]
Thanks. And have done about this.
